#include "keynames.hpp"

string keyname(int sdlkey){
	if (sdlkey == SDLK_BACKSPACE) return "Backspace";
	else if (sdlkey == SDLK_TAB) return "Tab";
	else if (sdlkey == SDLK_CLEAR) return "Clear";
	else if (sdlkey == SDLK_RETURN) return "Return";
	else if (sdlkey == SDLK_PAUSE) return "Pause";
	else if (sdlkey == SDLK_ESCAPE) return "Esc";
	else if (sdlkey == SDLK_SPACE) return "Space";
	else if (sdlkey == SDLK_EXCLAIM) return "!";
	else if (sdlkey == SDLK_QUOTEDBL) return "\"";
	else if (sdlkey == SDLK_HASH) return "#";
	else if (sdlkey == SDLK_DOLLAR) return "Dollar";
	else if (sdlkey == SDLK_AMPERSAND) return "&";
	else if (sdlkey == SDLK_QUOTE) return "'";
	else if (sdlkey == SDLK_LEFTPAREN) return "(";
	else if (sdlkey == SDLK_RIGHTPAREN) return ")";
	else if (sdlkey == SDLK_ASTERISK) return "*";
	else if (sdlkey == SDLK_PLUS) return "+";
	else if (sdlkey == SDLK_COMMA) return ",";
	else if (sdlkey == SDLK_MINUS) return "-";
	else if (sdlkey == SDLK_PERIOD) return ".";
	else if (sdlkey == SDLK_SLASH) return "/";
	else if (sdlkey == SDLK_0) return "0";
	else if (sdlkey == SDLK_1) return "1";
	else if (sdlkey == SDLK_2) return "2";
	else if (sdlkey == SDLK_3) return "3";
	else if (sdlkey == SDLK_4) return "4";
	else if (sdlkey == SDLK_5) return "5";
	else if (sdlkey == SDLK_6) return "6";
	else if (sdlkey == SDLK_7) return "7";
	else if (sdlkey == SDLK_8) return "8";
	else if (sdlkey == SDLK_9) return "9";
	else if (sdlkey == SDLK_COLON) return ":";
	else if (sdlkey == SDLK_SEMICOLON) return ";";
	else if (sdlkey == SDLK_LESS) return "Less";
	else if (sdlkey == SDLK_EQUALS) return "=";
	else if (sdlkey == SDLK_GREATER) return "More";
	else if (sdlkey == SDLK_QUESTION) return "?";
	else if (sdlkey == SDLK_AT) return "At";
	else if (sdlkey == SDLK_LEFTBRACKET) return "[";
	else if (sdlkey == SDLK_BACKSLASH) return "Backslash";
	else if (sdlkey == SDLK_RIGHTBRACKET) return "]";
	else if (sdlkey == SDLK_CARET) return "Caret";
	else if (sdlkey == SDLK_UNDERSCORE) return "Underscore";
	else if (sdlkey == SDLK_BACKQUOTE) return "Grave";
	else if (sdlkey == SDLK_a) return "A";
	else if (sdlkey == SDLK_b) return "B";
	else if (sdlkey == SDLK_c) return "C";
	else if (sdlkey == SDLK_d) return "D";
	else if (sdlkey == SDLK_e) return "E";
	else if (sdlkey == SDLK_f) return "F";
	else if (sdlkey == SDLK_g) return "G";
	else if (sdlkey == SDLK_h) return "H";
	else if (sdlkey == SDLK_i) return "I";
	else if (sdlkey == SDLK_j) return "J";
	else if (sdlkey == SDLK_k) return "K";
	else if (sdlkey == SDLK_l) return "L";
	else if (sdlkey == SDLK_m) return "M";
	else if (sdlkey == SDLK_n) return "N";
	else if (sdlkey == SDLK_o) return "O";
	else if (sdlkey == SDLK_p) return "P";
	else if (sdlkey == SDLK_q) return "Q";
	else if (sdlkey == SDLK_r) return "R";
	else if (sdlkey == SDLK_s) return "S";
	else if (sdlkey == SDLK_t) return "T";
	else if (sdlkey == SDLK_u) return "U";
	else if (sdlkey == SDLK_v) return "V";
	else if (sdlkey == SDLK_w) return "W";
	else if (sdlkey == SDLK_x) return "X";
	else if (sdlkey == SDLK_y) return "Y";
	else if (sdlkey == SDLK_z) return "Z";
	else if (sdlkey == SDLK_DELETE) return "Delete";
	else if (sdlkey == SDLK_KP0) return "Keypad 0";
	else if (sdlkey == SDLK_KP1) return "Keypad 1";
	else if (sdlkey == SDLK_KP2) return "Keypad 2";
	else if (sdlkey == SDLK_KP3) return "Keypad 3";
	else if (sdlkey == SDLK_KP4) return "Keypad 4";
	else if (sdlkey == SDLK_KP5) return "Keypad 5";
	else if (sdlkey == SDLK_KP6) return "Keypad 6";
	else if (sdlkey == SDLK_KP7) return "Keypad 7";
	else if (sdlkey == SDLK_KP8) return "Keypad 8";
	else if (sdlkey == SDLK_KP9) return "Keypad 9";
	else if (sdlkey == SDLK_KP_PERIOD) return "Keypad .";
	else if (sdlkey == SDLK_KP_DIVIDE) return "Keypad /";
	else if (sdlkey == SDLK_KP_MULTIPLY) return "Keypad *";
	else if (sdlkey == SDLK_KP_MINUS) return "Keypad -";
	else if (sdlkey == SDLK_KP_PLUS) return "Keypad +";
	else if (sdlkey == SDLK_KP_ENTER) return "Keypad enter";
	else if (sdlkey == SDLK_KP_EQUALS) return "Keypad =";
	else if (sdlkey == SDLK_UP) return "Up";
	else if (sdlkey == SDLK_DOWN) return "Down";
	else if (sdlkey == SDLK_RIGHT) return "Right";
	else if (sdlkey == SDLK_LEFT) return "Left";
	else if (sdlkey == SDLK_INSERT) return "Insert";
	else if (sdlkey == SDLK_HOME) return "Home";
	else if (sdlkey == SDLK_END) return "End";
	else if (sdlkey == SDLK_PAGEUP) return "Page up";
	else if (sdlkey == SDLK_PAGEDOWN) return "Page down";
	else if (sdlkey == SDLK_F1) return "F1";
	else if (sdlkey == SDLK_F2) return "F2";
	else if (sdlkey == SDLK_F3) return "F3";
	else if (sdlkey == SDLK_F4) return "F4";
	else if (sdlkey == SDLK_F5) return "F5";
	else if (sdlkey == SDLK_F6) return "F6";
	else if (sdlkey == SDLK_F7) return "F7";
	else if (sdlkey == SDLK_F8) return "F8";
	else if (sdlkey == SDLK_F9) return "F9";
	else if (sdlkey == SDLK_F10) return "F10";
	else if (sdlkey == SDLK_F11) return "F11";
	else if (sdlkey == SDLK_F12) return "F12";
	else if (sdlkey == SDLK_F13) return "F13";
	else if (sdlkey == SDLK_F14) return "F14";
	else if (sdlkey == SDLK_F15) return "F15";
	else if (sdlkey == SDLK_NUMLOCK) return "Num lock";
	else if (sdlkey == SDLK_CAPSLOCK) return "Caps lock";
	else if (sdlkey == SDLK_SCROLLOCK) return "Scroll lock";
	else if (sdlkey == SDLK_RSHIFT) return "Right shift";
	else if (sdlkey == SDLK_LSHIFT) return "Left shift";
	else if (sdlkey == SDLK_RCTRL) return "Right control";
	else if (sdlkey == SDLK_LCTRL) return "Left control";
	else if (sdlkey == SDLK_RALT) return "Right alt";
	else if (sdlkey == SDLK_LALT) return "Left alt";
	else if (sdlkey == SDLK_RMETA) return "Right meta";
	else if (sdlkey == SDLK_LMETA) return "Left meta";
	else if (sdlkey == SDLK_LSUPER) return "Left win";
	else if (sdlkey == SDLK_RSUPER) return "Right win";
	else if (sdlkey == SDLK_MODE) return "Mode shift";
	else if (sdlkey == SDLK_HELP) return "Help";
	else if (sdlkey == SDLK_PRINT) return "Print screen";
	else if (sdlkey == SDLK_SYSREQ) return "Sysrq";
	else if (sdlkey == SDLK_BREAK) return "Break";
	else if (sdlkey == SDLK_MENU) return "Menu";
	else if (sdlkey == SDLK_POWER) return "Power";
	else if (sdlkey == SDLK_EURO) return "Euro";
	else return "???";
}
